add enabled property to item
OpenTimelineIO/otio-fcp-adapter pull request #3
Opened 2023-10-18 21:31 UTC by nebukadhezer

2023-10-19 10:58 UTC, apetrynet commented
Hi @nebukadhezer !
This looks like a good fix. Could you please fix the DCO issue by following the guide in the "Details" of failed test above?
It would also be great with a unit test for this addition. A super simple xml file with two clips which each have the enabled true/false or something would be awesome.

2023-10-19 11:10 UTC, nebukadhezer commented
Hey @apetrynet I will add a simple test and also look for the other types that can carry the enabled property and see if we can propagate them too. But it might take some days not sure when I can fiddle it in.

2023-10-19 11:13 UTC, apetrynet commented
Thanks! No rush :)

2023-11-07 19:47 UTC, nebukadhezer commented
@apetrynet  I added a simple unittest, let me know if this should be more, also I used "each_clip", "find_clips" does not exist in my otio version 0.15.0

2023-11-07 19:47 UTC, nebukadhezer commented
ahh and I used the track name info if there is one to name the tracks according to the info in the fcp xml.

2023-11-09 13:37 UTC, apetrynet requested changes
Thank you for adding unit tests.
I enabled the CI to run them which found some lint issues. If you want to run a lint check locally please look at the `.github/workflows/ci.yaml` for inspiration on how to run it.

2023-11-09 13:37 UTC, apetrynet commented on src/otio_fcp_adapter/fcp_xml.py
> +                                                       track_name),
I think this will throw an exception if `track_metadata` is `None`
Perhaps resolve the name outside of the Track instantiation?

2023-11-09 13:37 UTC, apetrynet commented on tests/test_fcp7_xml_adapter.py
> +        self.assertTrue(list(timeline.tracks[0].each_clip())[0].enabled)
Since we're close to releases which replace `each_clip` with `find_clips` would it be possible to do this in a way that doesn't need update in the near future?
Could you index the clips directly in the track? `self.assertFalse(timeline.tracks[2][0])` (adjust index if you have a gap or something before the clip)

2023-11-09 13:37 UTC, apetrynet commented on tests/test_fcp7_xml_adapter.py
> +        self.assertEqual(timeline.tracks[2].name, "disabled_track")
Do we have an example of an unnamed track in another xml file so we can test the "old" fallback behavior?

2023-11-09 14:31 UTC, nebukadhezer commented on src/otio_fcp_adapter/fcp_xml.py
> +                                                       track_name),
moved it up.

2023-11-09 14:31 UTC, nebukadhezer commented on tests/test_fcp7_xml_adapter.py
> +        self.assertTrue(list(timeline.tracks[0].each_clip())[0].enabled)
removed each clip as suggested.

2023-11-09 14:32 UTC, nebukadhezer commented on tests/test_fcp7_xml_adapter.py
> +        self.assertEqual(timeline.tracks[2].name, "disabled_track")
added 2 more test on audio tracks and one is not named, at least in my test this is how they all look like then

2023-11-09 14:34 UTC, nebukadhezer commented
In regards to the linter it asked for one line in the unittest I did not touch, I added it, but I wonder if that is all, as it exists right after the first error. Is this intentional so CI time is saved ?

```Run flake8 --show-source --statistics --ignore=E501,W503,W504
  flake8 --show-source --statistics --ignore=E501,W503,W504
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.17/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.17/x64/lib
./tests/test_fcp7_xml_adapter.py:38:1: E30[2](https://github.com/OpenTimelineIO/otio-fcp-adapter/actions/runs/6795623326/job/18524280881#step:6:2) expected 2 blank lines, found 1
class TestFcp7XmlUtilities(unittest.TestCase, test_utils.OTIOAssertions):
^
1     E[3](https://github.com/OpenTimelineIO/otio-fcp-adapter/actions/runs/6795623326/job/18524280881#step:6:3)02 expected 2 blank lines, found 1
Error: Process completed with exit code 1.```

2023-11-09 15:27 UTC, apetrynet commented on src/otio_fcp_adapter/fcp_xml.py
> +                                                           track_name) if track_metadata else track_name)
```suggestion
        if track_metadata:
            track_name = track_metadata.get("fcp_xml", {}).get("@MZ.TrackName", track_name)
```
Just a suggestion to avoid initializing `track_name` twice if not necessary and perhaps a bit easier on the eyes.

2023-11-09 20:48 UTC, nebukadhezer commented on src/otio_fcp_adapter/fcp_xml.py
> +                                                           track_name) if track_metadata else track_name)
done

2023-11-10 13:18 UTC, apetrynet approved these changes
LGTM!
Thank you for your contribution @nebukadhezer!

2023-11-10 13:30 UTC, merged